# Generated by Django 5.0.7 on 2024-08-10 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_remove_prospect_contact_alter_prospect_contact_ptr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('non_prospect_individual', 'Non-Prospect Individual'), ('church', 'Church'), ('prospect', 'Prospect')], default='prospect', max_length=30),
        ),
    ]
