# Generated by Django 5.0.7 on 2024-08-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_contact_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='year_founded',
            field=models.DateField(blank=True, null=True),
        ),
    ]
