# Generated by Django 5.0.7 on 2024-08-10 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_church_year_founded'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='church',
            options={'verbose_name': 'Church', 'verbose_name_plural': 'Churches'},
        ),
    ]
