# Generated by Django 5.0.7 on 2024-08-04 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(choices=[('Base Mobilizer', 'Base Mobilizer'), ('Regional Mobilizer', 'Regional Mobilizer'), ('Golbal Team', 'Global Team'), ('Mobilization Director', 'Mobilization Director'), ('Office Executive Director', 'Office Executive Director'), ('Other', 'Other')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
